<a href="https://colab.research.google.com/github/Pushkar0655g/Generative-AI/blob/main/A1_GEN_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**QUESTION 1**

In [1]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
actual = np.array([20, 30, 40, 50, 60])
predicted = np.array([20.5, 30.3, 40.2, 50.6, 60.7])
mae = np.mean(np.abs(actual - predicted))
mse = np.mean((actual - predicted) ** 2)
r_squared = 1 - (np.sum((actual - predicted) ** 2) / np.sum((actual - np.mean(actual)) ** 2))
mae_sklearn = mean_absolute_error(actual, predicted)
mse_sklearn = mean_squared_error(actual, predicted)
r_squared_sklearn = r2_score(actual, predicted)
print("Custom MAE:", mae)
print("Custom MSE:", mse)
print("Custom R²:", r_squared)
print("Sklearn MAE:", mae_sklearn)
print("Sklearn MSE:", mse_sklearn)
print("Sklearn R²:", r_squared_sklearn)

Custom MAE: 0.4600000000000016
Custom MSE: 0.24600000000000147
Custom R²: 0.99877
Sklearn MAE: 0.4600000000000016
Sklearn MSE: 0.24600000000000147
Sklearn R²: 0.99877


**QUESTION 2**

In [4]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
y_a = [0, 0, 1, 1, 2, 0, 0, 1, 0, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 2]
y_p = [0, 0, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2]
def calc_acc(y_a, y_p):
    c = sum([1 for a, p in zip(y_a, y_p) if a == p])
    return c / len(y_a)
def calc_cm(y_a, y_p, n_c):
    m = np.zeros((n_c, n_c), dtype=int)
    for a, p in zip(y_a, y_p):
        m[a][p] += 1
    return m
n_c = len(set(y_a))
acc = calc_acc(y_a, y_p)
cm = calc_cm(y_a, y_p, n_c)
lib_acc = accuracy_score(y_a, y_p)
lib_cm = confusion_matrix(y_a, y_p)
print("Accuracy (from scratch):", acc)
print("Confusion Matrix (from scratch):\n", cm)
print("\nUsing Libraries:")
print("Accuracy (library):", lib_acc)
print("Confusion Matrix (library):\n", lib_cm)

Accuracy (from scratch): 0.8636363636363636
Confusion Matrix (from scratch):
 [[6 0 1]
 [1 6 0]
 [1 0 7]]

Using Libraries:
Accuracy (library): 0.8636363636363636
Confusion Matrix (library):
 [[6 0 1]
 [1 6 0]
 [1 0 7]]
